### ISSUE TITLE
Show XYZ coordinates of stations (showstats)

### ISSUE THREAD

**Issue by tschaffter** [Phiwa/DragonTravel#18]
Possibly add also the coordinates of the waypoints when entering /dt showflights.

**Comment by Phiwa** [comment]
I can do that for stations, but it is too much for Flights, I think.
I could put the first and the last waypoint there, but for flights with more than 10 waypoints, it would be a pain.

**Comment by tschaffter** [comment]
The bukkit plugin [Brewery](http://www.curse.com/bukkit-plugins/minecraft/brewery) provides a clean solution to this issue. A player would is too drunk is kicked from the server. When he logs in back and depending on the "quality" of the alcohol he drank, he will wake up at a place picked randomly among a list of wakeup points defined by an admin beforehand.

To get the list of wakeup points: /brew wakeup list

![2015-04-15_19 46 25](https://cloud.githubusercontent.com/assets/3056480/7165696/71fce5a6-e3a9-11e4-885f-2d670dc475fc.png)

To tp to the wakeup point <id>: /brew wakeup check <id>

![2015-04-15_19 48 50](https://cloud.githubusercontent.com/assets/3056480/7165716/92d9357c-e3a9-11e4-81b0-b7e2c7b7762f.png)

There is also a way to tp successively to every wakeup points using /brew wakeup check. At each destinations, the player can kick in the air with his fist to tp to the next wakeup point or enter a command to cancel the checking of the wakeup points.

The list of station could be displayed in the same way as the wakeup points using /dt showstats.

The list of flights could be displayed in the same way as the stations with an ID and possibly the taking off and landing coordinates. The list of all the waypoints of a flight could be obtained using the command /pt showflight <flight ID>.

**Comment by Phiwa** [comment]
Had a similar idea, I think you could also show some more information like an estimated travel time etc. in the details.

**Comment by tschaffter** [comment]
That would be great!

**Comment by Phiwa** [comment]
I finally added this (sorry, totally forgot about those issues...) - commit 7dcec3dbf7949f414335d1b0114ba9133e627db2

For stations, this is included in the normal output of "/dt showstats".
For flights, this is included in a new command "/dt showflight <flightname>" (output is too long to include in "/dt showflights" command.

![dt_showstats_coords](https://cloud.githubusercontent.com/assets/1133120/20033141/7a66e150-a370-11e6-9159-bcb7bbfa124c.png)
![dt_showflight_wp_coords](https://cloud.githubusercontent.com/assets/1133120/20033140/7a6362c8-a370-11e6-8d6e-ee34e4f76aa2.png)

I will colour the output a bit more in the future, but the basic functionality will be included in the next version of DT. :)

**Comment by Phiwa** [comment]
Added colours to output (commit d8cde7e49b64bf46f72a11e4cf28450f4e5d9ca2). :)

**Comment by tschaffter** [comment]
Thanks!
