### ISSUE TITLE
Add support to Essentials Eco

### ISSUE THREAD

**Issue by tschaffter** [Phiwa/DragonTravel#20]
Essentials is one of the most used plugin for Minecraft. That would be great if travels/flights could be paid using the credits from Essential Economy.

http://ess.khhq.net/wiki/Essentials_Economy

**Comment by Phiwa** [comment]
If I got that right, Vault already supports Essentials Eco.

Quote from the Vault project page:

"Vault currently Supports:
[...]
- Econ: 
[...]
  - EssentialsEcon"

Source: http://dev.bukkit.org/bukkit-plugins/vault/

**Comment by Phiwa** [comment]
Verified this using the Wiki of Essentials Economy you linked above, so this issue is solved.
