### ISSUE TITLE
Master doesn't build

### ISSUE THREAD

**Issue by tschaffter** [Phiwa/DragonTravel#21]
The target can not be build using "mvn package".

...
Downloaded: http://repo.gravitydevelopment.net/net/gravitydevelopment/anticheat/AntiCheat/2.0.2/AntiCheat-2.0.2.pom (4 KB at 11.1 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.796s
[INFO] Finished at: Thu Apr 02 17:17:48 CEST 2015
[INFO] Final Memory: 5M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project DragonTravel: Could not resolve dependencies for project eu.phiwa:DragonTravel:jar:0.0.1.5: Failed to collect dependencies for [org.bukkit:craftbukkit:jar:1.8.3-R0.1-SNAPSHOT (compile), net.milkbowl.vault:VaultAPI:jar:1.4 (provided), com.massivecraft:factions:jar:2.3.1 (system), com.massivecraft:mcore:jar:7.1.0 (system), fr.neatmonster:ncpplugin:jar:static (compile), net.gravitydevelopment.anticheat:AntiCheat:jar:2.0.2 (compile)]: Failed to read artifact descriptor for org.bukkit:bukkit:jar:1.7.9-R0.1-SNAPSHOT: Could not transfer artifact org.bukkit:bukkit:pom:1.7.9-R0.1-SNAPSHOT from/to herocraft-repo (http://ci.herocraftonline.com//plugin/repository/everything/): ci.herocraftonline.com: Unknown host ci.herocraftonline.com -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by Phiwa** [comment]
Since Factions (and Mcore) do not offer maven repositories, you need to register them as local repositories before.
Since the Craftbukkit maven is not available anymore, you need to register it as a local repository as well, I guess. I'm open for any better solution. ;)
Feel free to adjust everything necessary, the workaround using local repos is crap.

**Comment by tschaffter** [comment]
One solution could be to add the missing packages DragonTravel requires to [Maven Central Repository](http://search.maven.org/) or [jCentral](https://bintray.com/bintray/jcenter).

Did you have the time to look at the other issues I reported? I just tested again with the latest release of Spigot 1.8.3 (master branch). Unfortunately there are still too many issues to use DragonTravel, which I would really like to do.

**Comment by Phiwa** [comment]
I never worked with the central repository before, but if you have experience with it, feel free to create a PR.
Sadly, I did not have any time to work on DragonTravel yet, but I hope to be able to work on at least one or two bugs this week.

**Comment by Phiwa** [comment]
Still reworking some things, there are some projects whose maven repositories are not reachable anymore which leaves us with some problems. I currently use system-scope dependencies, but we need to find a different solution without uploading them to the central repository which might cause licensing issues for us...

**Comment by Phiwa** [comment]
This issue should be at least solved partly. CB JARs are still needed locally, but all other JARs have been replaced by maven repositories (thanks @games647 ).
Work on replacing CB JARs with maven repositories will be done, but the basic issue has been solved.
