### ISSUE TITLE
Payment is taken even though station doesn't exist

### ISSUE THREAD

**Issue by L-E-iT** [Phiwa/DragonTravel#37]
When using the /dt travel <station> command, the player's money will be taken even if the station does not exist.

**Comment by Phiwa** [comment]
I found and hopefully fixed the problem, fix will be included in the next release.

**Comment by L-E-iT** [comment]
Thanks!  Looking forward to it.

**Comment by Phiwa** [comment]
Included in v01.006.05 which is currently under review.
