### ISSUE TITLE
Issue with skylight

### ISSUE THREAD

**Issue by L-E-iT** [Phiwa/DragonTravel#38]
Players who attempt to travel between stations and are standing on either carpet or half on/off a half slab receive an error about not being able to see skylight.  This also deducts money to my knowledge, and cancels the flight.  

The players are given dt.travel.* and some of them dt.nocost.*

The only flight method that is turned on is Stations, and the skylight option is turned off in the config (RequireSkyLight: false).

At the moment these are my notes on the topic.  It took me a while to figure out what was bugging out about it, but I think this is it:

Users cannot fly when standing on top of a carpet
Users cannot fly when standing half on and half off a half slab
dt.admin.* and dt.ignoreusestation.* do not fix this
dt.* does fix this

If you want to chat further about this and see it for yourself I am more than happy to jump into another form of communication. We used your plugin a lot before and would love to continue using it now.

**Comment by Phiwa** [comment]
Wow, thanks for the detailed analysis! I would totally like to chat with you on that topic! Feel free to send me a PM (e.g. at BukkitDev), so we can plan on some chat (e.g. Skype). I already have the topic "skylight" on my todo list, but this analysis will really help with it! :)

**Comment by Phiwa** [comment]
Will have to postpone that until next week, sorry.

**Comment by Phiwa** [comment]
I guess I found the problem. I'll try to implement a fix and test it. Will contact you if I get stuck somewhere. :)

**Comment by Phiwa** [comment]
I hope the basic problem is fixed now, at least my tests did not show this behavior anymore.
However, the problem about players being charged for cancelled travels still exists and will hopefully be fixed in the next release. 
Please test it as soon as the new version has been reviewed and give me feedback on the carpet/half-step issue. :)

**Comment by Phiwa** [comment]
Skylight bug has been fixed, confirmed via private message.
