### ISSUE TITLE
Kingdoms support

### ISSUE THREAD

**Issue by renzotom** [Phiwa/DragonTravel#40]
Hello, can you add support for plugin https://www.spigotmc.org/resources/kingdoms-battle-for-land-might-and-glory-1-8-8-1-11.11833/ (there is also free version or you can ask author for free premium version to do support, or ask him for help) Kingdoms? It is like factions, but there are more options.

**Comment by Phiwa** [comment]
You asked on BukkitDev already, I guess. No need for another comment here. ;)

For everybody else, the reason why this is running with low priority on my todo list: https://dev.bukkit.org/projects/dragontravel?comment=2191

If there is someone willing to develop (and test) this feature, you are welcome to create a pull request.

**Comment by renzotom** [comment]
Oh sorry I created issue instead pull request :D

**Comment by Phiwa** [comment]
I guess, I can close the issue... ;)
