### ISSUE TITLE
Wiki is down

### ISSUE THREAD

**Issue by iCaitlyn** [Phiwa/DragonTravel#68]
Your wiki now just shows the link for a nitrado . net site.

**Comment by Phiwa** [comment]
Thank you for your report!
Seems like there was a problem with the automatic renewal of certificates on my hoster's side...
Wiki should be up and accessible again.

**Comment by iCaitlyn** [comment]
So.... I hate to literally dig up an old issue, but your wiki is down again now...

Could I suggest perhaps migrating it to a place like GitBook or Github's own Wiki, or even a Github Pages site, where you may not need to worry about the hosting or domain name not being renewed?

**Comment by Phiwa** [comment]
I migrated my webspace to another hoster and since I barely saw any traffic on the wiki anyway, I did not migrate it.
I now migrated the wiki, so it should be accessible again.
