### ISSUE TITLE
Can't build, because your Maven repository is empty

### ISSUE THREAD

**Issue by Sailoriae** [Phiwa/DragonTravel#69]
Hello !
I wanted to update your plugin to Minecraft 1.16.2, but your Maven repository server is empty : http://maven.phiwa.eu
Also, its SSL certificate is invalid.
Is it possible for you to restore it ? Or do I have to modify `pom.yml` ?
Thank you for your answer, and have a nice day !

**Comment by Phiwa** [comment]
Sorry, seems to be related to #68, forgot about the other subdomain...

I just fixed it, you should be able to use the repository!

Thank you for the report! :)

**Comment by Sailoriae** [comment]
Hello ! ^^
Thank you for this fix, but the following JAR file is empty :
https://maven.phiwa.eu/org/spigot/spigot-v1_15_R1/v1_15_R1/spigot-v1_15_R1-v1_15_R1.jar

**Comment by Phiwa** [comment]
Strange, didn't realize the empty file before because of my local cache... ;)
Re-uploaded the file, it should work now.
