### ISSUE TITLE
Server shutdown/restart: Remove travelling dragons and teleport players to start location

### ISSUE THREAD

**Issue by Phiwa** [Phiwa/DragonTravel#72]
When a server is shut down/restarted, all dragons travelling in that moment should be removed and their riders should be teleported to the start location.
This prevents "free dragons" from flying around after the next start.

Report: https://www.spigotmc.org/threads/dragontravel.82654/page-6#post-4012481

**Comment by bmack94** [comment]
See #79 
This will remove orphaned dragons (if they are in a loaded chunk) and place riders to a save location and delete them afterwards.

**Comment by Phiwa** [comment]
MR #79 looks good.

Thanks @bmack94!
