### ISSUE TITLE
Support for 1.19?

### ISSUE THREAD

**Issue by MrRagtime** [Phiwa/DragonTravel#84]

**Comment by Phiwa** [comment]
To be honest: I haven't played Minecraft in nine years and haven't found time to actively work on DragonTravel in years.
I'll take a look at the open merge request, but if that does not work I don't think I'll update DT for 1.19 in the nearer future.

**Comment by MrRagtime** [comment]
I understand you may not have the time to update DragonsTraval so instead of this, can I have permission to base a Skript off of DragonsTraval?

**Comment by Phiwa** [comment]
DragonTravel is published under the BSD 2-clause license, so as long as you follow the rules defined by the license you can use the code or fork the whole project.

**Comment by MrRagtime** [comment]
I'll look into the license when I get a chance.
ty
